name: Node CI

on: [push]

jobs:

  library:
    name: "Library"
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 8.x

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
         ${{ runner.os }}-yarn-

    - name: yarn install
      run: yarn
    - name: lint js
      run: yarn lint:js
    - name: lint hbs
      run: yarn lint:hbs
    - name: typecheck
      run: yarn typecheck
    - name: tests
      run: yarn test

  docs:
    name: "Docs"
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 8.x

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
         ${{ runner.os }}-yarn-

    - name: yarn install library
      run: yarn --production
    - name: yarn install docs
      # Absurdly, yarn always fails on the first try here.
      # https://github.com/yarnpkg/yarn/issues/2629
      run: until yarn install; do echo "Retrying yarn"; done
      working-directory: docs
    - name: lint js
      run: yarn lint:js
      working-directory: docs
    - name: lint hbs
      run: yarn lint:hbs
      working-directory: docs
    - name: tests
      run: yarn test
      working-directory: docs

  compat:
    name: "Compat"
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        try-scenario: [ember-lts-3.8, ember-lts-3.12, ember-release, ember-beta, ember-canary, ember-default-with-jquery, ember-classic]
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 8.x

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
         ${{ runner.os }}-yarn-

    - name: yarn install
      run: yarn

    - name: test
      run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}


